% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  12pt,
]{article}
\usepackage{lmodern}
\usepackage{amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
  \usepackage{amssymb}
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={ Data Mining: Problem Set 1},
  pdfauthor={Suabyi Thao},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{\includegraphics[width=4.5in,height=\textheight]{long_logo.png}\\
Data Mining: Problem Set 1}
\author{Suabyi Thao\footnote{\textbf{Email}
  \href{mailto:sthao19@hamline.edu}{\nolinkurl{sthao19@hamline.edu}}.
  \textbf{Position} Analytics Student}}
\date{September 13, 2023}

\begin{document}
\maketitle

\begin{quote}
The purpose of this document is to simulataneously analyze data on US
crime rates and become more familiar with the syntax and abilities of
R-markdown to combine code and analysis in a progressional document.
Blockquotes look better in HTML typically, but you can see their general
effect in any document. The text is highlighted differently in RStudio
so you know its part of the block quote. Also, the margins of the text
in the final document are narrower to separate the block quote from
normal text.
\end{quote}

\hypertarget{the-structure-of-the-data}{%
\section{The Structure of the Data}\label{the-structure-of-the-data}}

This data set contains statistics, in arrests per 100,000 residents for
assault, murder, and rape in each of the US states in 1973. It has 50
observations, one for each state. As an additional variable, urban
population is also accounted for. Urban population is represented as the
percent of the population living in urban areas.

\begin{verbatim}
## 'data.frame':    50 obs. of  4 variables:
##  $ Murder  : num  13.2 10 8.1 8.8 9 7.9 3.3 5.9 15.4 17.4 ...
##  $ Assault : int  236 263 294 190 276 204 110 238 335 211 ...
##  $ UrbanPop: int  58 48 80 50 91 78 77 72 80 60 ...
##  $ Rape    : num  21.2 44.5 31 19.5 40.6 38.7 11.1 15.8 31.9 25.8 ...
\end{verbatim}

\begin{verbatim}
## NULL
\end{verbatim}

The data set has 50 observations with 4 columns. These columns are
\texttt{Murder}, \texttt{Assault}, \texttt{UrbanPop}, and \texttt{Rape}.
The \texttt{Murder}variable is a numeric data type, as in the
\texttt{Rape} variable. The \texttt{Assault} and \texttt{UrbanPop}
variables are integers.

\hypertarget{summary-of-features}{%
\subsection{Summary of Features}\label{summary-of-features}}

\begin{longtable}[]{@{}lllll@{}}
\toprule
& Murder & Assault & UrbanPop & Rape\tabularnewline
\midrule
\endhead
& Min. : 0.800 & Min. : 45.0 & Min. :32.00 & Min. : 7.30\tabularnewline
& 1st Qu.: 4.075 & 1st Qu.:109.0 & 1st Qu.:54.50 & 1st
Qu.:15.07\tabularnewline
& Median : 7.250 & Median :159.0 & Median :66.00 & Median
:20.10\tabularnewline
& Mean : 7.788 & Mean :170.8 & Mean :65.54 & Mean :21.23\tabularnewline
& 3rd Qu.:11.250 & 3rd Qu.:249.0 & 3rd Qu.:77.75 & 3rd
Qu.:26.18\tabularnewline
& Max. :17.400 & Max. :337.0 & Max. :91.00 & Max. :46.00\tabularnewline
\bottomrule
\end{longtable}

Across all 50 states, the \textbf{mean} of the \emph{Murder} variable
is7.79 arrests for murder per 100,000 people. While the \textbf{mean} of
\emph{Assault} is 170.76 arrests per 100,000 people. \emph{UrbanPop} has
a \textbf{mean} of 65.54, and \emph{Rape} has a \textbf{mean} of 21.23.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Make sure that this code block shows up in the final document}
\CommentTok{\# and that the resulting plot does also.}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(tidyr)}
\NormalTok{scaled\_data }\OtherTok{=} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{sapply}\NormalTok{(USArrests, scale))}
\FunctionTok{ggplot}\NormalTok{(}\FunctionTok{gather}\NormalTok{(scaled\_data, cols, value), }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ value)) }\SpecialCharTok{+} 
       \FunctionTok{geom\_histogram}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{..density..), }\AttributeTok{bins =} \DecValTok{10}\NormalTok{) }\SpecialCharTok{+} 
       \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{alpha=}\NormalTok{.}\DecValTok{2}\NormalTok{, }\AttributeTok{fill=}\StringTok{"\#FF6666"}\NormalTok{) }\SpecialCharTok{+}
       \FunctionTok{facet\_grid}\NormalTok{(.}\SpecialCharTok{\textasciitilde{}}\NormalTok{cols) }\SpecialCharTok{+}
       \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Feature Histograms for the Scaled US Arrests Data"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\includegraphics{data_mining_ps1_files/figure-latex/unnamed-chunk-4-1.pdf}
\caption{Histogram of Scaled Data}
\end{figure}

It appears that there may be some slight right -skew to the
\texttt{Murder}variable and perhaps the \texttt{Rape} variable. This
tells us that for both of these variables the \textbf{mean} is greater
than the \textbf{median}. \texttt{Assault} seems to also have a
right-skew because its \textbf{mean} is a lot greater than its assault,
with a \textbf{mean} of 170.76 and a \textbf{median} of
159.\texttt{UrbanPop} seems to be a left-skew which tells us that the
mean is less than the median, with a \textbf{mean} of 65.54 and a
\textbf{median} of 66.

\hypertarget{relationships-between-features}{%
\subsection{Relationships Between
Features}\label{relationships-between-features}}

\begin{figure}
\centering
\includegraphics{data_mining_ps1_files/figure-latex/unnamed-chunk-5-1.pdf}
\caption{Facet Grid of Scatter Plots}
\end{figure}

The scatter plots shows that there may be a positive correlation between
\texttt{Murder} and \texttt{Assault}. Generally, a positive correlation
in this case tells us that as population increase, the rate of
\texttt{Murder} and \texttt{Assault} will also increase. The
\texttt{Rape} variable also seems to show some sort of linear as well.
The scatter plot for the \texttt{UrbanPop} variable seems to be
nonlinear. This tells us that an increase in population may or may not
result an increase or decrease in the rate of crime in each state.

\begin{longtable}[]{@{}ll@{}}
\toprule
\textbf{Variable} & \textbf{Mean}\tabularnewline
\midrule
\endhead
Murder & 7.788\tabularnewline
Assault & 170.76\tabularnewline
UrbanPop & 65.54\tabularnewline
Rape & 21.232\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{machine-learning-questions}{%
\section{Machine Learning Questions}\label{machine-learning-questions}}

In this section, you will type your paragraph answers to the following
questions presented below. Do your best to answer the questions after
reading chapter 1 of the textbook and watching the assigned videos.

\hypertarget{what-are-the-7-basic-steps-of-machine-learning}{%
\subsection{What are the 7 basic steps of machine
learning?}\label{what-are-the-7-basic-steps-of-machine-learning}}

\hypertarget{in-your-own-words-please-explain-the-bias-variance-tradeoff-in-supervised-machine-learning-and-make-sure-to-include-proper-terminology.}{%
\subsection{In your own words, please explain the bias-variance tradeoff
in supervised machine learning and make sure to include proper
terminology.}\label{in-your-own-words-please-explain-the-bias-variance-tradeoff-in-supervised-machine-learning-and-make-sure-to-include-proper-terminology.}}

\hypertarget{explain-in-your-own-words-why-cross-validation-is-important-and-useful.}{%
\subsection{Explain, in your own words, why cross-validation is
important and
useful.}\label{explain-in-your-own-words-why-cross-validation-is-important-and-useful.}}

\end{document}
